version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: git clone https://github.com/ingydotnet/git-subrepo /usr/local/git-subrepo
      - run: echo 'source /usr/local/git-subrepo/.rc' >> ~/.bashrc
      - checkout
      - run: git subrepo pull --all
      - run: make
      - run: ./test
      - run: ls -l test-dev*
      - run: make -C test-devel1
      - run: test-devel1/test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build

