version: 2.1

jobs:
  build:
    docker:
      - image: desmonddak/new-git-test:0.0.1
    steps:
      - run: sudo git clone https://github.com/ingydotnet/git-subrepo /usr/local/git-subrepo
      - run: echo 'source /usr/local/git-subrepo/.rc' >> ~/.bashrc
      - checkout
      - run: git --version
      - run: cat /usr/local/git-subrepo/.rc
      - run: source ~/.bashrc && git subrepo pull --all
      - run: make
      - run: ./test
      - run: ls -l test-dev*
      - run: make -C test-devel1
      - run: test-devel1/test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build

