version: 2.1

jobs:
  build:
    docker:
      - image: desmonddak/new-git:latest
    steps:
      - run: git clone https://github.com/ingydotnet/git-subrepo /usr/local/git-subrepo
      - run: echo 'source /usr/local/git-subrepo/.rc' >> ~/.bashrc
      - run: echo '' >> ~/.bashrc
      - checkout
      - run: git --version
      - run: git config --get user.name
      - run: cat /usr/local/git-subrepo/.rc
      - run: cat ~/.bashrc
      - run: source ~/.bashrc && printenv
      - run: cat ~/.bashrc && source ~/.bashrc && echo $GIT_SUBREPO_ROOT && echo $CIRCLE_JOB
      - run: source /usr/local/git-subrepo/.rc && echo $GIT_SUBREPO_ROOT
      - run: git config --global user.email "root@root.com"
      - run: git config --global user.name "root"
      - run: source /usr/local/git-subrepo/.rc && git subrepo pull --all
      - run: make
      - run: ./test
      - run: ls -l test-dev*
      - run: make -C test-devel1
      - run: test-devel1/test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

